test Docker push

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -49,98 +49,98 @@ jobs:
     steps:
       - name: Check out repo ⬇️
         uses: actions/checkout@v2
-
-      - name: Set up R ▶️
-        uses: r-lib/actions/setup-r@master
-        if: matrix.config.image == null
-        with:
-          r-version: ${{ matrix.config.r }}
-
-      - name: Install remotes 🔭
-        run: |
-          install.packages('remotes')
-        shell: Rscript {0}
-
-      - name: Set BiocManager version 📆
-        if: matrix.config.image == null
-        run: |
-          install.packages('BiocManager')
-          BiocManager::install(version = "${{ matrix.config.bioc }}", ask = FALSE)
-        shell: Rscript {0}
-
-      - name: Query dependencies ❓
-        run: |
-          saveRDS(remotes::dev_package_deps(dependencies = TRUE, repos = c(getOption('repos'), BiocManager::repositories())), 'depends.Rds', version = 2)
-        shell: Rscript {0}
-
-      - name: Cache R packages 💾
-        if: runner.os != 'Windows' && matrix.config.image == null
-        uses: actions/cache@v1
-        with:
-          path: ${{ env.R_LIBS_USER }}
-          key: ${{ runner.os }}-r-${{ matrix.config.r }}-bioc-${{ matrix.config.bioc }}-${{ hashFiles('depends.Rds') }}
-          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-bioc-${{ matrix.config.bioc }}-
-
-      - name: Install system dependencies 🔧
-        if: runner.os == 'Linux'
-        env:
-          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
-        run: |
-          Rscript -e "remotes::install_github('r-hub/sysreqs')"
-          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
-          sudo -s eval "$sysreqs"
-          sudo apt-get update && sudo apt-get -y install libcurl4-openssl-dev
-
-      - name: Install dependencies 🔨
-        run: |
-          options(repos = c(CRAN = "https://cran.r-project.org"))
-          remotes::install_deps(dependencies = TRUE, repos = BiocManager::repositories(), Ncpus=2)
-          remotes::install_cran("rcmdcheck")
-          remotes::install_cran("covr")
-        shell: Rscript {0}
-
-      - name: Session info 🖥️ 
-        run: |
-          options(width = 100)
-          pkgs <- installed.packages()[, "Package"]
-          sessioninfo::session_info(pkgs, include_base = TRUE)
-        shell: Rscript {0}
-
-      - name: Check ✅ 
-        run: rcmdcheck::rcmdcheck(args = c("--no-manual"), error_on = "warning", check_dir = "check")
-        shell: Rscript {0}
-
-      - name: Check --as-cran ✅ ✅ 
-        if: github.event_name == 'schedule' && github.repository == 'mixOmicsTeam/mixOmics'
-        env:
-          _R_CHECK_CRAN_INCOMING_: false
-        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran", "--ignore-vignettes", "--run-dontrun"), error_on = "warning", check_dir = "check/asCRAN", build_args = c("--no-build-vignettes"))
-        shell: Rscript {0}
-      - name: BiocCheck 🧬 ✅
-        if: github.event_name == 'schedule' && github.repository == 'mixOmicsTeam/mixOmics'
-        run: |
-          BiocManager::install("BiocCheck")
-          BiocCheck::BiocCheck(".")
-        shell: Rscript {0}
-
-      - name: Upload check results ⬆️
-        if: failure()
-        uses: actions/upload-artifact@master
-        with:
-          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
-          path: check
-
-      - name: Show testthat output 📖
-        if: always()
-        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
-        shell: bash
-        
+# 
+#       - name: Set up R ▶️
+#         uses: r-lib/actions/setup-r@master
+#         if: matrix.config.image == null
+#         with:
+#           r-version: ${{ matrix.config.r }}
+# 
+#       - name: Install remotes 🔭
+#         run: |
+#           install.packages('remotes')
+#         shell: Rscript {0}
+# 
+#       - name: Set BiocManager version 📆
+#         if: matrix.config.image == null
+#         run: |
+#           install.packages('BiocManager')
+#           BiocManager::install(version = "${{ matrix.config.bioc }}", ask = FALSE)
+#         shell: Rscript {0}
+# 
+#       - name: Query dependencies ❓
+#         run: |
+#           saveRDS(remotes::dev_package_deps(dependencies = TRUE, repos = c(getOption('repos'), BiocManager::repositories())), 'depends.Rds', version = 2)
+#         shell: Rscript {0}
+# 
+#       - name: Cache R packages 💾
+#         if: runner.os != 'Windows' && matrix.config.image == null
+#         uses: actions/cache@v1
+#         with:
+#           path: ${{ env.R_LIBS_USER }}
+#           key: ${{ runner.os }}-r-${{ matrix.config.r }}-bioc-${{ matrix.config.bioc }}-${{ hashFiles('depends.Rds') }}
+#           restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-bioc-${{ matrix.config.bioc }}-
+# 
+#       - name: Install system dependencies 🔧
+#         if: runner.os == 'Linux'
+#         env:
+#           RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
+#         run: |
+#           Rscript -e "remotes::install_github('r-hub/sysreqs')"
+#           sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
+#           sudo -s eval "$sysreqs"
+#           sudo apt-get update && sudo apt-get -y install libcurl4-openssl-dev
+# 
+#       - name: Install dependencies 🔨
+#         run: |
+#           options(repos = c(CRAN = "https://cran.r-project.org"))
+#           remotes::install_deps(dependencies = TRUE, repos = BiocManager::repositories(), Ncpus=2)
+#           remotes::install_cran("rcmdcheck")
+#           remotes::install_cran("covr")
+#         shell: Rscript {0}
+# 
+#       - name: Session info 🖥️ 
+#         run: |
+#           options(width = 100)
+#           pkgs <- installed.packages()[, "Package"]
+#           sessioninfo::session_info(pkgs, include_base = TRUE)
+#         shell: Rscript {0}
+# 
+#       - name: Check ✅ 
+#         run: rcmdcheck::rcmdcheck(args = c("--no-manual"), error_on = "warning", check_dir = "check")
+#         shell: Rscript {0}
+# 
+#       - name: Check --as-cran ✅ ✅ 
+#         if: github.event_name == 'schedule' && github.repository == 'mixOmicsTeam/mixOmics'
+#         env:
+#           _R_CHECK_CRAN_INCOMING_: false
+#         run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran", "--ignore-vignettes", "--run-dontrun"), error_on = "warning", check_dir = "check/asCRAN", build_args = c("--no-build-vignettes"))
+#         shell: Rscript {0}
+#       - name: BiocCheck 🧬 ✅
+#         if: github.event_name == 'schedule' && github.repository == 'mixOmicsTeam/mixOmics'
+#         run: |
+#           BiocManager::install("BiocCheck")
+#           BiocCheck::BiocCheck(".")
+#         shell: Rscript {0}
+# 
+#       - name: Upload check results ⬆️
+#         if: failure()
+#         uses: actions/upload-artifact@master
+#         with:
+#           name: ${{ runner.os }}-r${{ matrix.config.r }}-results
+#           path: check
+# 
+#       - name: Show testthat output 📖
+#         if: always()
+#         run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
+#         shell: bash
+#         
       - name: Inject slug/short variables
         uses: rlespinasse/github-slug-action@v3.x
 
       - name: Push to DockerHub
         if: >
-            github.event_name != 'schedule' && github.repository == 'mixOmicsTeam/mixOmics' && "${{ env.GITHUB_REF_SLUG }}"  == "master"
+            github.event_name != 'schedule' && github.repository == 'aljabadi/mixOmics' && "${{ env.GITHUB_REF_SLUG }}"  == "master"
         uses: docker/build-push-action@v1
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
